set(OpenGL_GL_PREFERENCE GLVND)
find_package(OpenGL REQUIRED)
find_package(SDL2 REQUIRED CONFIG REQUIRED COMPONENTS SDL2)

set(IMGUI_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/imgui)
set(IMGUI_BACKEND_INCLUDE_DIR ${IMGUI_INCLUDE_DIR}/backends)
file(GLOB IMGUI_HEADERS ${IMGUI_INCLUDE_DIR}/*.h)
file(GLOB IMGUI_SOURCES ${IMGUI_INCLUDE_DIR}/*.cpp)
file(GLOB IMGUI_BACKEND_HEADERS ${IMGUI_BACKEND_INCLUDE_DIR}/*.h)
file(GLOB IMGUI_BACKEND_SOURCES ${IMGUI_BACKEND_INCLUDE_DIR}/*.cpp)

add_library(imgui STATIC ${IMGUI_SOURCES} ${IMGUI_BACKEND_INCLUDE_DIR}/imgui_impl_sdl2.cpp ${IMGUI_BACKEND_INCLUDE_DIR}/imgui_impl_sdlrenderer2.cpp)

add_definitions(-DIMGUI_IMPL_OPENGL_LOADER_GLAD)

include_directories(
    ${IMGUI_INCLUDE_DIR}
    ${IMGUI_BACKEND_INCLUDE_DIR}
    ${OPENGL_INCLUDE_DIR}
    ${SDL2_INCLUDE_DIR})

target_link_libraries(imgui
    ${OPENGL_LIBRARIES}
    ${SDL2_LIBRARIES})

set_target_properties(imgui PROPERTIES LINKER_LANGUAGE CXX)
set_target_properties(imgui PROPERTIES FOLDER ${IMGUI_INCLUDE_DIR})
set(IMGUI_LIBRARIES imgui)
